-- Inventory hardening for POS Bengkel Josjis
-- Run this once in the Supabase SQL Editor before using inactive parts/restock history.

alter table public.part
  add column if not exists aktif boolean not null default true;

create table if not exists public.restock_history (
  id bigint generated by default as identity primary key,
  part_id uuid not null references public.part(id) on delete cascade,
  jumlah integer not null check (jumlah > 0),
  stok_sebelum integer not null default 0,
  stok_sesudah integer not null default 0,
  keterangan text,
  created_at timestamptz not null default now()
);

create index if not exists restock_history_part_id_idx on public.restock_history(part_id);
create index if not exists restock_history_created_at_idx on public.restock_history(created_at desc);

alter table public.part enable row level security;
alter table public.restock_history enable row level security;

-- This app currently uses the Supabase anon client. Keep these policies aligned
-- with the existing project policy model if RLS is already configured.
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'part' and policyname = 'public app can read parts') then
    create policy "public app can read parts" on public.part for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'part' and policyname = 'public app can write parts') then
    create policy "public app can write parts" on public.part for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'restock_history' and policyname = 'public app can read restock history') then
    create policy "public app can read restock history" on public.restock_history for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'restock_history' and policyname = 'public app can write restock history') then
    create policy "public app can write restock history" on public.restock_history for insert with check (true);
  end if;
end $$;
